
tr:
  title: "Bilgisayar Mühendisliği | Boğaziçi Üniversitesi"
  languageName: Türkçe
  copyright: Telif hakkı © {year} Bilgisayar Mühendisliği Bölümü, Boğaziçi Üniversitesi. Tüm hakları saklıdır.
  weight: 1

en:
  title: "Computer Engineering | Boğaziçi University"
  languageName: English
  copyright: Copyright © {year} Department of Computer Engineering, Boğaziçi University. All rights reserved.
  weight: 2
